### ISSUE TITLE
大佬能否写一个京东超市的收取蓝币？

### ISSUE THREAD

**Issue by starjason** [MasterSumCloud/YangmaoHelper#1]
入口：京东app首页，找到“京东超市”，底部“京小超”，点击进入。
需求：需要实时监控售货员头顶上，不定时会出现蓝币，如果出现就立即收取蓝币。

**Comment by MasterSumCloud** [comment]
未发现入口

**Comment by MasterSumCloud** [comment]
未发现入口

**Comment by starjason** [comment]
上传3张截图
![Inked01_LI](https://user-images.githubusercontent.com/16408594/89608902-f2554000-d8a8-11ea-8b14-2416f6da9b78.jpg)
![Inked02_LI](https://user-images.githubusercontent.com/16408594/89608907-f5503080-d8a8-11ea-9728-f8f2e36c8ee4.jpg)
![Inked03_LI](https://user-images.githubusercontent.com/16408594/89608909-f6815d80-d8a8-11ea-992c-6c7c79ab39e1.jpg)

**Comment by MasterSumCloud** [comment]
每个人不一样  我的这个不是

**Comment by starjason** [comment]
那你可以在顶部的搜索栏里面搜索“京东超市”，第一个京东超市字样的点进去，就是第2个截图。

**Comment by MasterSumCloud** [comment]
每个人中间不一样 懂？我的就是推荐的商品

**Comment by MasterSumCloud** [comment]
每个人中间不一样 懂？我的就是推荐的商品

**Comment by starjason** [comment]
搜索栏里面搜索“京东超市”
